### ISSUE TITLE
node.js not installed as part of web.sh

### ISSUE THREAD

**Issue by seanknox** [donnemartin/dev-setup#16]
Heya,

After running `./dots all` I noticed node wasn't installed, though according to the [documentation](https://github.com/donnemartin/dev-setup#nodejs) it should be. Am I missing anything?

**Comment by donnemartin** [comment]
Doh, looks like I never removed the 'coming soon' from `.dots`:

https://github.com/donnemartin/dev-setup/blob/master/.dots#L88

This line `web.sh` should install it:

https://github.com/donnemartin/dev-setup/blob/master/web.sh#L21

Interested in a pull request to enable `web.sh` from `.dots`? :)

**Comment by seanknox** [comment]
Can do!
