### ISSUE TITLE
[Question] Modification / Contribution

### ISSUE THREAD

**Issue by gristel** [donnemartin/dev-setup#17]
Hi.

Let me start by saying that I really love what you've done (and are still doing) here.
I'm putting together a 'small' gitbook on Bash Scripting and I was wondering if I could use your project for demonstration purposes?
Mind that I will break it apart and most likely modify quite a few things, but it will end up doing the exact same thing, but with things I need on my dev machine added and those I don't need eliminated.

If you agree to this, how should I proceed? Fork the project and create my own repo and keep you posted on updates and make a pull request for the changes you like? Or any other suggestion on making a 'collaboration' as smooth as possible?

Thanks a lot in advance!

**Comment by donnemartin** [comment]
Hi Gristel,

Thanks for the feedback!  A gitbook on Bash scripting sounds great, sure feel free to use `dev-setup` as a resource.

>Fork the project and create my own repo and keep you posted on updates and make a pull request for the changes you like?

I suppose you could either 1) clone and create a new repo or 2) fork.  Feel free to send me updates--pull requests on `dev-setup` are always welcome, the fork route might make it easier to sync changes.

-Donne

**Comment by gristel** [comment]
Hi Donne,

I just finished the theoretical part. You have have a preview at https://gristel.gitbooks.io/bash-scripting/content/. Please tell me if you're OK with the credits or if you want me to add something.

For now, I will put the scripts in a new repo, because they will change drastically during the writing of the book. But you might want to follow me on that repo, so you can check progress and tell me if you see an approach you like, for future pull requests on your repo.
You can find it at https://github.com/gristel/bash-scripting-dotfiles

/gristel

**Comment by gristel** [comment]
Hi Donne,

I will need a bit more time, since I just got notice from Ryan Chadwick that I'm not allowed to use any of the information on his website in any way in my gitbook. So I'm gonna rewrite the whole Shebang ;-)

**Comment by donnemartin** [comment]
Ok, thanks for the update...I'm going to close this issue, please feel free to email me with questions/updates and good luck with the gitbook!
