### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by royassaly** [donnemartin/dev-setup#21]
In the iTerm2 section (https://github.com/donnemartin/dev-setup#iterm2), where it says:

$ curl -O https://raw.githubusercontent.com/donnemartin/mac-dev-setup/master/.aliases

should be:

$ curl -O https://raw.githubusercontent.com/donnemartin/dev-setup/master/.aliases

Great README by the way.

**Comment by donnemartin** [comment]
Thanks for the feedback, nice catch!  Interested in submitting a pull request? :)

**Comment by royassaly** [comment]
Done!

**Comment by donnemartin** [comment]
Fixed with https://github.com/donnemartin/dev-setup/pull/22.
