### ISSUE TITLE
Update for MacOS

### ISSUE THREAD

**Issue by desmo90** [donnemartin/dev-setup#50]
Please add the macos dotfile and update the dot-script

**Comment by donnemartin** [comment]
Hi @desmo90, are you seeing issues on macOS?  I'm running macOS (through an upgrade from 10.11 where I last ran the dev-setup scripts) and am not seeing issues.

**Comment by donnemartin** [comment]
I suppose you might need to run:

     $ sudo chown -R $(whoami) /usr/local

[Reference](https://github.com/Homebrew/brew/issues/385)
