### ISSUE TITLE
'./.dots all' calls webdev.sh called instead of web.sh

### ISSUE THREAD

**Issue by mike-u** [donnemartin/dev-setup#51]
I was just trying to install all without changing anything and got:

```

Setting up JavaScript web development environment.

------------------------------

./.dots: line 88: ./webdev.sh: No such file or directory

------------------------------

Setting up Android development environment.

```

I think it meant to call web.sh instead.

**Comment by donnemartin** [comment]
Hi @mike-u, thanks for the report!  Seems I renamed webdev.sh to web.sh in the past but forgot to update the .dots script.  Are you interested in submitting a pull request for a fix?

**Comment by mike-u** [comment]
Sure, I'll do one now.
