### ISSUE TITLE
Do I need to clean the repo files in ~ directory?

### ISSUE THREAD

**Issue by chenxingyu-cs** [donnemartin/dev-setup#53]
I used bootstrap.sh and I found that all the repo files appeared in ~ directory. Do I need to delete these files?
Thank you!

**Comment by donnemartin** [comment]
Hi @chenxingyu-cs, you can safely delete those files from the home directory and use the ones from the local dev-setup directory instead.

There's a PR in the works that will address this in the future: https://github.com/donnemartin/dev-setup/pull/42
