### ISSUE TITLE
Bash autocomplete does not work

### ISSUE THREAD

**Issue by shawnzam** [donnemartin/dev-setup#56]
When I open terminal and try to tab to autocomplete 
```-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]

me at hnt in ~
$ cd De-bash: printf: `words[0]': not a valid identifier
-bash: printf: `words[1]': not a valid identifier
-bash: compopt: command not found```

**Comment by donnemartin** [comment]
Hi @shawnzam, can you provide more details on how you ran into this issue?  Was it from a fresh install of dev-setup?  After some config changes?

What platform are you running on?

Are you using bash 4?  https://github.com/spf13/cobra/issues/240

**Comment by shawnzam** [comment]
I am sorry, I forget to update this, but a reinstall of the library resolved the issue. Kindly close this issue.

**Comment by donnemartin** [comment]
Thanks for the reply!
