### ISSUE TITLE
Support for QuickLookPlugins

### ISSUE THREAD

**Issue by bmkmanoj** [donnemartin/dev-setup#7]
This is an enhancement request. 
Can you include the instructions to install the [quick look plugins](https://github.com/sindresorhus/quick-look-plugins) as a post installation/set up step? I have found this immensely helpful, as a developer.

**Comment by donnemartin** [comment]
@bmkmanoj thanks for the tip, those look great.  Do you see this as an addition to the README, or something that should go into say, `brew.sh`?

**Comment by bmkmanoj** [comment]
These can go to README but as brew.sh already includes many others, I think, it is better to keep these as well as part of that.

**Comment by donnemartin** [comment]
@bmkmanoj sounds good.  Are you interested in submitting a pull request? :)

**Comment by bmkmanoj** [comment]
I have submitted the pull request - modified the brew.sh. I forgot to modify the README though, you may update the README.md for the same.

**Comment by donnemartin** [comment]
Note: See #8 for pull request.

**Comment by donnemartin** [comment]
Fixed with cc3ebf7b1b26e5c87139720bbd50ae923019fe4a.
