### ISSUE TITLE
iTerm color theme support in Ubuntu Gnome-terminal

### ISSUE THREAD

**Issue by nipunsadvilkar** [donnemartin/dev-setup#71]
@donnemartin : I really liked your iTerm2 theme, it's really beautiful. since I am using Ubuntu 14.04 with gnome-terminal, How can I get the same theme with font and colour in the gnome terminal?

**Comment by donnemartin** [comment]
Hi @nipunsadvilkar thanks for the feedback!  Sorry for the delayed response, been super busy lately.  Unfortunately, my response isn't all that helpful--I'm not sure how to get the same theme in gnome terminal.
