### ISSUE TITLE
softwareupdate: invalid option -- v

### ISSUE THREAD

**Issue by gitetsu** [donnemartin/dev-setup#84]
Hi.
In [osxprep.sh#L13](https://github.com/donnemartin/dev-setup/blob/master/osxprep.sh#L13]),
```
sudo softwareupdate -iva
```

But I found,
```
$ sudo softwareupdate -v
softwareupdate: invalid option -- v
$ defaults read loginwindow SystemVersionStampAsString
10.12.6
```

Same error occured on `10.13.3`.

We might need detect osx version and switch options, or simply delete `-v`.

I don't have other osx so I cannot confirm from which version this error occurs.

**Comment by donnemartin** [comment]
@gitetsu thanks for reporting, this should be fixed with #90.
