### ISSUE TITLE
setup fail under macOS High Sierra

### ISSUE THREAD

**Issue by congcong009** [donnemartin/dev-setup#88]
I tried 3 times and I still got error like below. 
![screen shot 2018-07-05 at 13 42 21](https://user-images.githubusercontent.com/2680017/42404322-9b3c0bba-81ba-11e8-95a0-063272b2d24e.png)

Meanwhile my terminal showed above message every time.
![screen shot 2018-07-06 at 23 30 21](https://user-images.githubusercontent.com/2680017/42404358-d61721c0-81ba-11e8-8847-98b838db1711.png)

My system info as below:
macOS High Sierra 10.13.5

**Comment by johnwyles** [comment]
Where does this come from?

**Comment by johnwyles** [comment]
I will also add that these issues happen with bash autocompletion:

```$ ls -al /Applicat[TAB]-bash: printf: `words[0]': not a valid identifier
-bash: printf: `words[1]': not a valid identifier
-bash: printf: `words[2]': not a valid identifier
-bash: ${prev,,}: bad substitution
```
