### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by johnwyles** [donnemartin/dev-setup#91]
This looks like this might be a dead or dying project but I find the feature very useful when it is needed. Unfortunately when you need this is only once every couple of years. However, with the premise of a community project, it needs to be up to date practically daily.

That said, it looks like within a half-day this project could be cleaned up - bug fixes closed, PRs doctored or merged/closed. I would be happy to handle this for now but perhaps transferring ownership or showing a little more TLC once a week could really help a ton of other engineers developers found starting a new job or setting up a new machine at home they just bought.  Thoughts?

**Comment by adityarpillai** [comment]
I’m actually writing a project very similar to this with Ansible. When I did a little bit of research, I came across this repository. In contrast to this repository however, Ansible easily allows you to customize what the user wants to be installed as well as have more flexibility than shell scripts. 

If you want to contribute to a project that will receive a lot of TLC, feel free to join me. 

https://github.com/adityarpillai/macOS-developer-setup

**Comment by johnwyles** [comment]
this one appears a bit out of date - i made one of my own a couple of months ago: https://github.com/johnwyles/bootstrap-macos - there is also one that caught my eye: https://github.com/joeyhoer/starter - a large majority of them are out of date so save yourself some time and start with these two and if you find something else or roll your own please share it back here!

**Comment by johnwyles** [comment]
@dportabella new laptop for christmas? 🤣

**Comment by dportabella** [comment]
cool, i took a look at https://github.com/johnwyles/bootstrap-macos and it seems up-to-date. I'll tailor it to my needs now.
It's actually not a new laptop; Just a fresh new installation. :)

**Comment by adityarpillai** [comment]
I actually renamed the project, it’s now at https://www.github.com/adityarpillai/jumpstart

I originally started out with a shell script similar to what you used, but for flexibility I modified the project to use Ansible. Documentation for how to use the script is fairly extensive, and I hope to keep it well documented so that people can clearly understand what the program does by default. 

Moreover, Ansible makes it really really easy to customize an installation, so I made the script first ask users what they want installed, then install based off the customization. This way, it’s really user-friendly without having to manually edit shell files.

**Comment by johnwyles** [comment]
yeah, I prefer a more generic approach. I wish I had caught wind of yours before I had already plowed through all the various fits-and-starts with min. The one I have written is not and very tailored and prescribed. I think a lot of the bit-rot of all these project stems from: a) the fact that once written  forget to contribute back to it or maintain it as the tools update / evolve / change b) (in my survey) there is no core one-size-fits-all solution or project that is forked from or maintained that is an excellent starting point (I hope yours can one day be @adityarpillai ?) c) people aren't starting from scratch often enough to maintain these projects or roll a new one d) there is a large disparity in the approach: ansible (i've seen a puppet based project a few years back), shell scripts, homebrew, some dockerize utilities, etc.

**Comment by dportabella** [comment]
i took a look at your repo jumpstart, but it seems mostly empty (no virtualbox, intellij, heroku, aws, mysql, core brew utils...).
the project is still under development, right?

**Comment by adityarpillai** [comment]
Yes, of course. I was playing around with the structure of the Ansible project first, getting customization to work with the installation of programs. Now that that’s done, I anticipate to include everything you mentioned and more.

**Comment by johnwyles** [comment]
@adityarpillai to get a jumpstart (heh) on flushing out your project you can pick-and-choose whatever you like from mine - no problem at all - all I want at the end of the day is a better way to manage this! I suggest finding a way to conscript whatever I have automatically into ansible. For some big early gains it seems like you could just hack together a script that will just throw a ton of scripts or commands that just run and install things without any configuration.  You could just throw a ton of these commands at your script and iterate through all of them to give you a flushed out ansibmle yaml file(s) that does all the command installations. Then the next deeper step would be to start flushing out all the files you want under configuration into a template (things like username, hostname, custom VIM settings, etc) as this work is less fruitful and more time consuming.

**Comment by johnwyles** [comment]
PS: Let's talk about this on whichever project page in a bug or some other means and not in this ticket - just `@` my github handle

**Comment by donnemartin** [comment]
Hey all, sorry been really busy.  I'm starting to free up and I plan to be more active with this project.

**Comment by johnwyles** [comment]
@donnemartin while it would be beneficial to merge in what PRs and clean up the issues here that you have I would also highly encourage you to look at what @adityarpillai has put together (https://github.com/adityarpillai/jumpstart) as an ansible (minor dependency) approach to what is a less prescriptive and more customizable/adaptive approach than either my project (https://github.com/johnwyles/bootstrap-macos) or this one.

I think that has actually been the most difficult thing to find when looking through (https://github.com/webpro/awesome-dotfiles) by @webpro. He is very particular about which projects he lets in and suffice it to say mine and @adityarpillai I think are great additions that he has declined PR's for in the past (see: https://github.com/webpro/awesome-dotfiles/pull/41). Your project could also point users to these other projects since @webpro has a more micromanagement style of curating his list and also perhaps help contribute to these approaches that take all the learnings from many of the projects outdated projects on @webpro 's (https://github.com/webpro/awesome-dotfiles), your very popular but more prescriptive approach (https://github.com/donnemartin/dev-setup), my very prescriptive approach (https://github.com/johnwyles/bootstrap-macos), and improves upon them (https://github.com/adityarpillai/jumpstart).

**Comment by donnemartin** [comment]
Thanks @johnwyles, I'll take a closer look and consider it.
